name: My First Workflow of Github Actions

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
  workflow_dispatch:

jobs:
  job01: 
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, Turma da disciplina Github Action.

